# Generated by Django 5.2.8 on 2026-06-13 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Direct URL to an image for this package",
                max_length=500,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("travel_date", models.DateField()),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Travel.package"
                    ),
                ),
            ],
        ),
    ]
